### ISSUE TITLE
Unknown status

### ISSUE THREAD

**Issue by nickletellier** [fatz/datadomain-monitoring#1]
I've implemented this and it seems that when all components are ok for IFSTATE and FSSPACE, Nagios interprets the overall status as UNKNOWN.

**Comment by fatz** [comment]
can you please provide me the line to reproduce this. I'll take a look into it

**Comment by fatz** [comment]
did you use the checks from the example: https://github.com/fatz/datadomain-monitoring/blob/master/nagios_check/check_datadomain.cfg#L31 ?

What overall status do you mean?...

**Comment by fatz** [comment]
i just found a typo in unknown output but i don't think this is what you meant fatz/datadomain-monitoring@f2eaa05f2b9b054bbbfca10ac90cafd0fa924d1e

**Comment by fatz** [comment]
i'm really sorry for the late response... the solution fatz/datadomain-monitoring@f771244ea5175d0deaab09797e2c8642b1aae513 is quite easy... i just forgot to exit 0. please check and let me know if it works for you
